-------------------------- MODULE MC_ComposedSym ---------------------------
(* Symmetry-quotiented TLC harness for the COMPOSED spec, used for the SCALED *)
(* 2 subs x 2 workers x 2 slots layering runs (#38) where the un-quotiented   *)
(* state space is large.                                                       *)
(*                                                                          *)
(* The three identity sets are interchangeable in the SAME way SubscriptionFence*)
(* (#37) quotients Workers/Subs:                                               *)
(*   - Subs   : the per-subscription fences are independent; a sub identity    *)
(*              appears only as an index, never as a value inside another      *)
(*              variable, so permuting Subs is sound.                          *)
(*   - Slots  : a slot identity appears only as an index of `slot` and as the  *)
(*              VALUE of subSlot[s]; subSlot is itself permutation-covariant    *)
(*              (a function Subs -> Slots), so permuting Slots is sound.        *)
(*   - Workers: a worker identity is an index of `token`, the VALUE of         *)
(*              sub[s].holder, the VALUE of slot[h].owner, and the `me`/`w`     *)
(*              action parameters.  The spec treats every worker uniformly     *)
(*              (no worker is named in any guard), so the holder/owner          *)
(*              registers are exactly the symmetric-register pattern TLA+       *)
(*              symmetry handles soundly -- identical to sub[s].holder ranging  *)
(*              over Workers in the #37 model, which uses Permutations(Workers).*)
(*                                                                          *)
(* SingleHolder / SingleOwner / Inv are all invariant under these permutations *)
(* (they only ever compare identities for equality), so the quotient preserves *)
(* every invariant verdict.  The un-quotiented MC_Composed is retained for the  *)
(* 1-slot runs and the Deposed-owner-late-write witness (legible named trace).  *)
EXTENDS Composed

Sym == Permutations(Workers) \cup Permutations(Subs) \cup Permutations(Slots)
=============================================================================
